{% set version = "1.0.5" %}

package:
  name: sphinxcontrib-applehelp
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinxcontrib-applehelp/sphinxcontrib-applehelp-{{ version }}.tar.gz
  sha256: e58ca6b828d1c9ef3f8b51ff5bfe989507399977da1bb389b393199d45066357

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - sphinx >=5

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.applehelp
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.sphinx-doc.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: sphinxcontrib-applehelp is a sphinx extension which outputs Apple help books
  doc_url: https://www.sphinx-doc.org/en/master/
  dev_url: https://github.com/sphinx-doc/sphinxcontrib-applehelp

extra:
  recipe-maintainers:
    - AA-Turner
    - conda-forge/sphinx
    - ocefpaf
